services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'ADMIN123'
      MYSQL_DATABASE: 'flask-auth-crud'
      MYSQL_ROOT_PASSWORD: 'ADMIN123'
    ports:
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - /DATABASE_CONTAINER/mysql:/var/lib/mysql